name: hi-fever
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aria2=1.23.0
  - bbmap=38.18
  - bedtools=2.31.0
  - biopython=1.84
  - blast=2.14.0
  - bzip2=1.0.8
  - c-ares=1.11.0
  - ca-certificates=2023.08.22
  - coreutils=8.25
  - curl=7.71.1
  - diamond=2.1.8
  - emboss=6.6.0
  - entrez-direct=16.2
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gawk=5.1.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - icu=72.1
  - krb5=1.17.2
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcurl=7.71.1
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=13.1.0
  - libgd=2.3.3
  - libglib=2.76.4
  - libgomp=13.1.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - libnsl=2.0.0
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.3.1
  - libwebp-base=1.3.1
  - libxml2=2.11.4
  - libzlib=1.2.13
  - mmseqs2=14.7e284
  - modin=0.32.0
  - ncbi-vdb=3.0.0
  - ncurses=6.4
  - nextflow=23.04.1
  - openjdk=11.0.1016
  - openssl=1.1.1w
  - pcre=8.45
  - pcre2=10.40
  - perl=5.32.1=4_hd590300_perl5
  - perl-archive-tar=2.40
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.62
  - perl-types-serialiser=1.01
  - pip=23.2.1
  - python=3.10.8_cpython
  - python_abi=3.10
  - readline=8.2
  - seqtk=1.4
  - setuptools=68.0.0
  - sqlite=3.42.0
  - taxonkit=0.15.0
  - tk=8.6.12
  - tzdata=2023c
  - wget=1.20.3
  - wheel=0.41.0
  - wise2=2.4.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - seqkit=2.8.2
